### PR TITLE
add env var TRAIN_BATCH_SIZE for training flexibility

### PR DESCRIPTION
**Pull request by kenthua**
Environment variable TRAIN_BATCH_SIZE setting for fine-tuning job, default to 1

### CODE REVIEW

**Review by karajendran — APPROVED** [review]

**Comment by arueth** [comment]
Setting it to `"1"` and not a placeholder variable like `"V_TRAIN_BATCH_SIZE"` is going to make it difficult to programmatically change.

**Comment by kenthua** [comment]
Trying to keep it 1 and always working, but in the docs guide is this fun'ness

`-i -e "/TRAIN_BATCH_SIZE/{n;s/1/${TRAIN_BATCH_SIZE}/}" \`

**Comment by arueth** [comment]
I think for consistency we should just use the placeholder variable. In the README you can set `TRAIN_BATCH_SIZE=1` and add a `-i -e "s|V_TRAIN_BATCH_SIZE|${TRAIN_BATCH_SIZE}|" \`

**Comment by kenthua** [comment]
sure, np, trying to make it hands off unless you explicitly want to change it, but it's in the table so we should be good.

**Review by arueth — APPROVED** [review]

**Review by karajendran — APPROVED** [review]

**Pull request merged**
